In [1]:
import numpy as np

In [2]:
# a tiny 6x6 'image' (just numbers for now)
image = np.array([
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
    [10, 10, 10, 0, 0, 0],
], dtype=float)

# a 3x3 kernel that detects a vertical edge (left-to-right change)
kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1],
], dtype=float)

print("image:\n", image.astype(int))
print("\nkernel (vertical-edge detector):\n", kernel.astype(int))

image:
 [[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]]

kernel (vertical-edge detector):
 [[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [8]:
out_img = np.zeros((4, 4))

out_img

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
out_img[0,0] = np.sum(image[0:3, 0:3] * kernel)

In [11]:
image[0:3, 1:4]

array([[10., 10.,  0.],
       [10., 10.,  0.],
       [10., 10.,  0.]])

In [12]:
out_img[0, 1] = np.sum(image[0:3, 1:4] * kernel)

In [13]:
out_img

array([[  0., -30.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [14]:
out_img[0, 2] = np.sum(image[0:3, 2:5]*kernel)

In [15]:
out_img

array([[  0., -30., -30.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [16]:
out_img[0, 3]  = np.sum(image[0:3, 3:6]*kernel)

In [17]:
out_img

array([[  0., -30., -30.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [18]:
out_img[1, 0] = np.sum(image[1:4, 0:3] * kernel)

In [19]:
out_img

array([[  0., -30., -30.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [30]:
np.pad(image, ((1, 1), (1, 1)), mode='constant')

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0., 10., 10., 10.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
image

array([[10., 10., 10.,  0.,  0.,  0.],
       [10., 10., 10.,  0.,  0.,  0.],
       [10., 10., 10.,  0.,  0.,  0.],
       [10., 10., 10.,  0.,  0.,  0.],
       [10., 10., 10.,  0.,  0.,  0.],
       [10., 10., 10.,  0.,  0.,  0.]])

In [ ]:
np.pad()