## Manual Implementation of Simple Linear Regression

In [1]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;
from sklearn.model_selection import train_test_split

In [4]:
dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
X,y

(array([[ 1.1],
        [ 1.3],
        [ 1.5],
        [ 2. ],
        [ 2.2],
        [ 2.9],
        [ 3. ],
        [ 3.2],
        [ 3.2],
        [ 3.7],
        [ 3.9],
        [ 4. ],
        [ 4. ],
        [ 4.1],
        [ 4.5],
        [ 4.9],
        [ 5.1],
        [ 5.3],
        [ 5.9],
        [ 6. ],
        [ 6.8],
        [ 7.1],
        [ 7.9],
        [ 8.2],
        [ 8.7],
        [ 9. ],
        [ 9.5],
        [ 9.6],
        [10.3],
        [10.5]]),
 array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
         54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
         61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
         98273., 101302., 113812., 109431., 105582., 116969., 112635.,
        122391., 121872.]))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [7]:
X_train

array([[ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [8]:
y_train

array([ 56642.,  66029.,  64445.,  61111., 113812.,  91738.,  46205.,
       121872.,  60150.,  39891.,  81363.,  93940.,  57189.,  54445.,
       105582.,  43525.,  39343.,  98273.,  67938.,  56957.])

In [11]:
x_mean = np.mean(X_train);
y_mean = np.mean(y_train);

In [12]:
x_mean

4.7299999999999995

In [13]:
y_mean

71022.5

In [40]:
x_minus_xmean = []
for i in X_train:
    a = x_minus_xmean.append(i-x_mean);

for i in 

sum(x_minus_xmean)

array([8.43769499e-15])

In [64]:
np.sum([x-x_mean for x in X_train])

8.43769498715119e-15

In [43]:
m = np.sum([(X_train[i]-x_mean)*(y_train[i]-y_mean) for i in range(len(X_train))])/np.sum([(x-x_mean)**2  for x in X_train]);

In [44]:
m

9345.942443122376

In [45]:
b = y_mean-(m*x_mean)

In [46]:
b

26816.19224403117

In [53]:
y = (m*1.5) + b
y

40835.10590871473

In [61]:
y_pred = np.array([((m*x) + b) for x in X_test])

In [62]:
y_pred

array([[ 40835.10590871],
       [123079.39940819],
       [ 65134.55626083],
       [ 63265.36777221],
       [115602.64545369],
       [108125.8914992 ],
       [116537.23969801],
       [ 64199.96201652],
       [ 76349.68719258],
       [100649.1375447 ]])

In [63]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431., 112635.,
        55794.,  83088., 101302.])

### Simplified Code

In [2]:
### Reading the Dataset 
dataset = pd.read_csv('Salary_Data.csv')

### Partition_Split Class
- A simple class that will partition the dataset into dependent and independent variables.
- And split the data into x_train, y_train, x_test, y_test.

In [3]:
class Partition_Split:

    def __init__(self, dataset):
        self.dataset = dataset;
        self.X, self.Y = self.dataset.iloc[:, :-1].values, self.dataset.iloc[:, -1].values;

    def dep_ind(self):
        return self.X, self.Y;
        
    def test_train_split(self, test_size):
        size = int(test_size/1*len(self.X));
        indices = np.arange(len(self.X));
        np.random.shuffle(indices);
        x_test = self.X[indices[:size]];
        x_train = self.X[indices[size:]];
        y_test = self.Y[indices[:size]];
        y_train = self.Y[indices[size:]];
        return x_train, y_train, x_test, y_test;

In [4]:
part = Partition_Split(dataset);

In [5]:
X, Y = part.dep_ind();

In [6]:
x_train, y_train, x_test, y_test = part.test_train_split(1/3);

### Implementation of Simple Linear Regression Class

In [7]:
class SimpleLinearRegression:

    def __init__(self):
        self.m = 0.0;
        self.b = 0.0;

    def fit(self, x_train, y_train):
        x_mean = np.mean(x_train);
        y_mean = np.mean(y_train);
        self.m = np.sum([(x_train[i]-x_mean)*(y_train[i]-y_mean) for i in range(len(x_train))])/np.sum([(x-x_mean)**2  for x in x_train]);
        self.b = y_mean-(self.m*x_mean);

    def predict(self, x_test):
        x_test = np.array(x_test);
        return (self.m * x_test) + self.b

In [8]:
regressor = SimpleLinearRegression();

In [9]:
regressor.fit(x_train, y_train);

In [10]:
y_predict = regressor.predict(x_test);

In [11]:
y_predict

array([[ 81730.70853436],
       [ 60894.2843358 ],
       [ 44793.41109145],
       [ 63735.61490833],
       [ 90254.70025196],
       [108249.79387799],
       [ 36269.41937386],
       [115826.67540474],
       [ 38163.63975555],
       [ 63735.61490833]])

In [12]:
y_test

array([ 81363.,  57189.,  43525.,  56957.,  91738., 109431.,  39343.,
       116969.,  46205.,  55794.])