In [1]:
import tensorflow as tf
from tensorflow import keras

In [13]:
from tensorflow.keras import Sequential

In [6]:
import numpy as np

In [5]:
l1 = keras.layers.Dense(units=4, activation='relu')

In [7]:
x = np.array([[1, 0]])

In [10]:
a1 = l1(x)
a1

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0.00235987, 0.        , 0.        , 0.13787985]], dtype=float32)>

In [9]:
l2 = keras.layers.Dense(units=1, activation="sigmoid")

In [11]:
l2(a1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.4698461]], dtype=float32)>

In [14]:
model = keras.Sequential([l1, l2])

In [15]:
model(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.4698461]], dtype=float32)>

In [26]:
m = keras.Sequential(
    [
        keras.layers.Input((2,)),
        keras.layers.Dense(units=4, activation='relu', name="Layer1"),
        keras.layers.Dense(units=1, activation='sigmoid', name="output layer")]
)

In [27]:
m(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6404532]], dtype=float32)>

In [28]:
m.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Layer1 (Dense)                  │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output layer (Dense)            │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17 (68.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:

prob = np.array([0.6, 0.2])

In [35]:
(prob >= 0.5).astype(int)

array([1, 0])

In [36]:
np.meshgrid([1, 2], [1, 2])

(array([[1, 2],
        [1, 2]]),
 array([[1, 1],
        [2, 2]]))

In [38]:
xx, yy = np.meshgrid(np.linspace(-3, 1.3, 200),  np.linspace(-3, 1.3, 200))

In [39]:
xx.shape

(200, 200)

In [40]:
yy.shape

(200, 200)

In [42]:
xx.ravel().shape

(40000,)